export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_LOADING_PRODUCTS = 'SET_LOADING_PRODUCTS';
export const SET_IS_FILTERED = 'SET_IS_FILTERED';
export const SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS';

export const SET_CART = 'SET_CART';
export const SET_LOADING_CART = 'SET_LOADING_CART';

export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const SET_LOADING_TRANSACTIONS = 'SET_LOADING_TRANSACTIONS';

export const EDIT_CART = "EDIT_CART";
export const DELETE_CART = "DELETE_CART";
export const ADD_CART = "ADD_CART";